# docker compose -f rabbitmq.yml up -d
services:
  rabbitmq:
    image: rabbitmq:4.2.3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
