# docker compose -f redis.yml up -d
services:
  redis:
    restart: always
    container_name: redis
    image: redis:8.4.0
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/redis'

volumes:
  redis_data:
    driver: local
